name: Go CI

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]  # optional, for releases
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Verify Go version
        run: go version

      - name: Install dependencies
        run: go mod download

      - name: Build binary
        run: go build -v -o etcd-benchmark-cleaner ./clean.go

      - name: Run tests (if you have them)
        run: |
          if [ -d "tests" ] || ls *_test.go >/dev/null 2>&1; then
            go test ./...
          else
            echo "No tests found."
          fi

      - name: Archive build artifact
        uses: actions/upload-artifact@v4
        with:
          name: etcd-benchmark-cleaner
          path: etcd-benchmark-cleaner


  release:
    name: Release on Tag
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: etcd-benchmark-cleaner

      - name: Release binary
        uses: softprops/action-gh-release@v1
        with:
          files: etcd-benchmark-cleaner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}